apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: gcp-demo
spec:
  terraformVersion: 1.0.0
  terraformRunnerPullPolicy: IfNotPresent
  # Pull this module to execute
  terraformModule: https://github.com/huan11/tf-repo.git//gcp-tf?ref=main

  # Use kubernetes as a backend which is available for terraform >= v0.13
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "simple-template-example"
        in_cluster_config  = true
      }
    }
  ignoreDelete: false
  writeOutputsToStatus: true
  keepCompletedPods: true

  # Create a tfvar env for the terraform to use
  env:
  - name: TF_VAR_name
    value: gcp-demo
  - name: TF_VAR_access_token
    value: 
  
  scmAuthMethods: [] # No keys are required to download or use this tf module
